kind: Service
apiVersion: v1
metadata:
  name: trackingms
  labels:
    app: trackingms
spec:
  type: NodePort
  selector:
    app: trackingms
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: trackingms
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: trackingms
        version: v1
    spec:
      containers:
      - name: trackingms
        image: trackingms
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
