kind: Service
apiVersion: v1
metadata:
  name: bookingms
  labels:
    app: bookingms
spec:
  type: NodePort
  selector:
    app: bookingms
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: bookingms
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bookingms
        version: v1
    spec:
      containers:
      - name: bookingms
        image: bookingms
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
